/* Writes ripes_tables.h, the read-only tables ripes.c searches with: the
 * quarter-turn successor of every permutation rank and every twist rank, and
 * the distance to solved of each within its own projection. They are computed
 * here, on the host, from solver.c's quarter_turn and rank_state, so the target
 * spends its instructions on the search alone.
 *
 * Each rank gets a row of FACES + 1 halfwords: its successor under each face,
 * then its depth. A successor is stored as the byte offset of its row, rank
 * times ROW_BYTES, rather than as the rank, so ripes.c finds an entry by adding
 * a column's byte offset to it, with no multiply by the row width or the entry
 * size.
 */
#define main solver_main
#include "solver.c"
#undef main

enum { FACES = 3, ROW_BYTES = 2 * (FACES + 1), UNSEEN = 0xFF };

static uint16_t permutation_move[PERMUTATIONS][FACES];
static uint16_t orientation_move[ORIENTATIONS][FACES];
static uint8_t permutation_depth[PERMUTATIONS];
static uint8_t orientation_depth[ORIENTATIONS];

/* Breadth-first distance to solved within one projection, one sweep of the
 * table per level, until a sweep finds nothing new. Returns the number of
 * entries reached. */
static uint16_t measure_depths(uint8_t *depth,
                               uint16_t (*move)[FACES],
                               uint16_t count)
{
    uint16_t reached = 1, before = 0;
    memset(depth, UNSEEN, count);
    depth[0] = 0;
    for (uint8_t level = 0; reached != before; ++level) {
        before = reached;
        for (uint16_t i = 0; i < count; ++i) {
            if (depth[i] != level)
                continue;
            for (uint8_t face = 0; face < FACES; ++face) {
                uint16_t next = i;
                for (uint8_t turn = 0; turn < 3; ++turn) {
                    next = move[next][face];
                    if (depth[next] == UNSEEN) {
                        depth[next] = (uint8_t) (level + 1);
                        ++reached;
                    }
                }
            }
        }
    }
    return reached;
}

static void print_table(const char *name,
                        uint16_t (*move)[FACES],
                        const uint8_t *depth,
                        uint16_t count)
{
    printf("static const uint16_t %s[%u][FACES + 1] = {\n", name, count);
    for (uint16_t i = 0; i < count; ++i)
        printf("%s{%u, %u, %u, %u},%s", i % 4 ? " " : "    ",
               move[i][0] * ROW_BYTES, move[i][1] * ROW_BYTES,
               move[i][2] * ROW_BYTES, depth[i],
               i % 4 == 3 || i + 1 == count ? "\n" : "");
    puts("};");
}

int main(void)
{
    state_t state;
    for (uint16_t rank = 0; rank < PERMUTATIONS; ++rank) {
        unrank_state((uint32_t) rank * ORIENTATIONS, &state);
        for (uint8_t face = 0; face < FACES; ++face) {
            state_t next = quarter_turn(state, face);
            permutation_move[rank][face] =
                (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    for (uint16_t rank = 0; rank < ORIENTATIONS; ++rank) {
        unrank_state(rank, &state);
        for (uint8_t face = 0; face < FACES; ++face) {
            state_t next = quarter_turn(state, face);
            orientation_move[rank][face] =
                (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
    if (measure_depths(permutation_depth, permutation_move, PERMUTATIONS) !=
            PERMUTATIONS ||
        measure_depths(orientation_depth, orientation_move, ORIENTATIONS) !=
            ORIENTATIONS) {
        fputs("a projection is not connected\n", stderr);
        return 1;
    }
    puts("/* Generated by gen_tables.c from solver.c's model; do not edit. */");
    print_table("permutation_table", permutation_move, permutation_depth,
                PERMUTATIONS);
    print_table("orientation_table", orientation_move, orientation_depth,
                ORIENTATIONS);
    return output_failed();
}
